sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t dudckd/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dudckd/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react
  env: Dockerreact-env-1
  bucket_name: elasticbeanstalk-ap-northeast-2-840213432037
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SCREAT_ACCESS_KEY