sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t dudckd/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dudckd/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: re-docker-react
  env: Redockerreact-env
  bucket_name: elasticbeanstalk-us-east-2-840213432037
  bucket_path: re-docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SCREAT_ACCESS_KEY